apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-jenkins
spec:
  selector:
    matchLabels:
      app: practice-jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: practice-jenkins
    spec:
      containers:
        - name: practice-jenkins
          image: surajkpvd/demo-project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: practice-jenkins
spec:
  ports:
    - port: 8072
      targetPort: 8072
      protocol: TCP
      name: tcp-practice-jenkins-port
  selector:
    app: practice-jenkins